require("core/options")
require("core/keymaps")

-- plugins
require('plugins/plugins')
require('plugins/nvim-tree')
require('plugins/treesitter')
-- require('plugins/lsp')
-- require('plugins/cmp')
require('plugins/comment')
-- require('plugins/autopairs')
require('plugins/bufferline')
require('plugins/gitsigns')
require('plugins/telescope')
require('plugins/colorscheme')
require('plugins/lualine')
